ansible:
  playbooks:
    wildcard:
      playbook: |
        - hosts: localhost
          connection: local
          gather_facts: false
          tasks:
            - debug:
                msg: "Wildcard cert updated"

      inventory: |
        [localhost]
        127.0.0.1

    abc:
      playbook: |
        - hosts: localhost
          connection: local
          gather_facts: false
          tasks:
            - debug:
                msg: "ABC cert updated"

      inventory: |
        [localhost]
        127.0.0.1

    xyz:
      playbook: |
        - hosts: localhost
          connection: local
          gather_facts: false
          tasks:
            - debug:
                msg: "XYZ cert updated"

      inventory: |
        [localhost]
        127.0.0.1
