apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificate-ui
  namespace: argocd   # Application objesi ArgoCD namespace'inde olacak
spec:
  project: default
  source:
    repoURL: 'https://github.com/aydincakfirat/certificate-automation'
    targetRevision: HEAD
    path: helm-charts/certificate-ui
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    #namespace: certificate-ui   # uygulamanın deploy olacağı namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
