# values.yaml
replicaCount: 1

image:
  repository: firataydincak/certificate-automation
  tag: v5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP   # NodePort yerine ClusterIP
  port: 80


ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

CronJob:
  enabled: true
  image:
    repository: alpine/ansible
    tag: latest
  schedule: "0 0 * * *"
  secretName: certificate-secrets

ansible:
  playbook: |
    - hosts: localhost
      connection: local
      gather_facts: false
      tasks:
        - name: Test
          debug:
            msg: "Certificate automation works"

  inventory: |
    [localhost]
    127.0.0.1

secrets:
  username: admin
  password: "123456"

fullnameOverride: ""
nameOverride: ""
