replicaCount: 1

image:
  repository: aydincakfirat/certificate-automation
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ansibleJob:
  enabled: true
  image:
    repository: aydincakfirat/certificate-automation
    tag: latest
  schedule: "0 0 * * *"
  secretName: certificate-secrets

fullnameOverride: ""
nameOverride: ""
