# values.yaml
replicaCount: 1

image:
  repository: firataydincak/certificate-automation
  tag: v5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP   # NodePort yerine ClusterIP
  port: 80


ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

CronJob:
  enabled: true
  image:
    repository: alpine/ansible
    tag: latest
  schedule: "0 0 * * *"
  secretName: certificate-secrets

ansible:
  selected: wildcard   # ArgoCD UI'dan burası değiştirilecek

  playbooks:
    wildcard:
      playbook: |
        - hosts: localhost
          connection: local
          gather_facts: false
          tasks:
            - debug:
                msg: "Wildcard cert updated"

      inventory: |
        [localhost]
        127.0.0.1

    abc:
      playbook: |
        - hosts: localhost
          connection: local
          gather_facts: false
          tasks:
            - debug:
                msg: "ABC cert updated"

      inventory: |
        [localhost]
        127.0.0.1

    xyz:
      playbook: |
        - hosts: localhost
          connection: local
          gather_facts: false
          tasks:
            - debug:
                msg: "XYZ cert updated"

      inventory: |
        [localhost]
        127.0.0.1

secrets:
  username: admin
  password: "123456"


fullnameOverride: ""
nameOverride: ""
