# values.yaml
replicaCount: 1

image:
  repository: firataydincak/certificate-automation
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP   # NodePort yerine ClusterIP
  port: 80


ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []


ansibleJob:
  enabled: true
  image:
    repository: aydincakfirat/certificate-automation
    tag: latest
  schedule: "0 0 * * *"
  secretName: certificate-secrets

fullnameOverride: ""
nameOverride: ""
