# values.yaml
replicaCount: 1

image:
  repository: firataydincak/certificate-automation
  tag: v5
  pullPolicy: IfNotPresent

service:
  type: ClusterIP   # NodePort yerine ClusterIP
  port: 80


ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

CronJob:
  enabled: true
  image:
    repository: alpine/ansible
    tag: latest
  schedule: "0 0 * * *"
  secretName: certificate-secrets

secrets:
  username: admin
  password: "123456"


CronJob:
  enabled: true
  image:
    repository: firataydincak/certificate-automation
    tag: v5
  schedule: "0 0 * * *"
  secretName: certificate-secrets

fullnameOverride: ""
nameOverride: ""
